#!/usr/bin/env python3
"""Generate the final accessible-source Supabase migration from reviewed artifacts."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FACTS = ROOT / "data/audit/final-accessible-facts.json"
REVIEW = ROOT / "data/audit/final-accessible-source-review.json"
DRIVE = ROOT / "data/source-images/reconciliation.jsonl"
OUTPUT = ROOT / "supabase/migrations/20261007000000_final_accessible_source_review.sql"


def q(value):
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def values(rows):
    return "\n  " + ",\n  ".join("(" + ",".join(q(v) for v in row) + ")" for row in rows)


def main():
    facts = json.loads(FACTS.read_text())
    review = json.loads(REVIEW.read_text())
    drive = [json.loads(line) for line in DRIVE.read_text().splitlines() if line.strip()]
    source_by_file = {row["filename"]: row["source_id"] for row in drive}
    if len(review["records"]) != 345 or len(facts["observed_teams"]) != 38:
        raise SystemExit("Final review or observed-team cardinality changed")

    sql = ["-- Generated by scripts/build-final-accessible-migration.py.",
           "-- Every row is tied to an individually inspected accessible source image.\n"]
    sql.append("""CREATE TABLE IF NOT EXISTS knowledge.source_review_resolutions (
  source_id bigint PRIMARY KEY REFERENCES knowledge.sources(source_id),
  corpus text NOT NULL,
  resolution_category text NOT NULL CHECK (resolution_category IN (
    'unreadable image','cropped text','ambiguous identity','duplicate',
    'irrelevant to the game database','visible information already represented',
    'visible new information requiring import','missing relationship or attribution'
  )),
  reviewed_on date NOT NULL,
  review_state text NOT NULL
);
ALTER TABLE knowledge.source_review_resolutions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON knowledge.source_review_resolutions FROM PUBLIC, anon, authenticated;
""")
    review_rows = [(r["source_id"], r["corpus"], r["resolution_category"], "2026-10-07", "individually_visually_reviewed") for r in review["records"]]
    sql.append("INSERT INTO knowledge.source_review_resolutions (source_id,corpus,resolution_category,reviewed_on,review_state) VALUES" + values(review_rows) + "\nON CONFLICT (source_id) DO UPDATE SET corpus=EXCLUDED.corpus,resolution_category=EXCLUDED.resolution_category,reviewed_on=EXCLUDED.reviewed_on,review_state=EXCLUDED.review_state;\n")
    sql.append("""CREATE TABLE IF NOT EXISTS knowledge.legendary_assault_tips (
  id text PRIMARY KEY,
  encounter_name text NOT NULL,
  exact_visible_text text NOT NULL,
  review_state text NOT NULL
);
CREATE TABLE IF NOT EXISTS knowledge.legendary_assault_tip_sources (
  tip_id text NOT NULL REFERENCES knowledge.legendary_assault_tips(id),
  source_id bigint NOT NULL REFERENCES knowledge.sources(source_id),
  PRIMARY KEY (tip_id, source_id)
);
CREATE TABLE IF NOT EXISTS knowledge.faction_rule_sources (
  rule_id text NOT NULL REFERENCES knowledge.faction_rules(id),
  source_id bigint NOT NULL REFERENCES knowledge.sources(source_id),
  PRIMARY KEY (rule_id, source_id)
);
ALTER TABLE knowledge.legendary_assault_tips ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge.legendary_assault_tip_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge.faction_rule_sources ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON knowledge.legendary_assault_tips, knowledge.legendary_assault_tip_sources, knowledge.faction_rule_sources FROM PUBLIC, anon, authenticated;
""")
    war_rows = [(r["id"], r["name"], r["outpost_victory_points"], r["exact_visible_effect"], r["exact_visible_phase_rule"], source_by_file[r["source_image"]], "screenshot_verified_current") for r in facts["war_outpost_rules"]]
    sql.append("INSERT INTO knowledge.war_outpost_rules (id,name,outpost_victory_points,exact_visible_effect,exact_visible_phase_rule,source_id,review_state) VALUES" + values(war_rows) + "\nON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,outpost_victory_points=EXCLUDED.outpost_victory_points,exact_visible_effect=EXCLUDED.exact_visible_effect,exact_visible_phase_rule=EXCLUDED.exact_visible_phase_rule,source_id=EXCLUDED.source_id,review_state=EXCLUDED.review_state;\n")
    tip_rows = [(r["id"], r["encounter"], r["exact_visible_text"], "screenshot_verified_current") for r in facts["legendary_assault_tips"]]
    tip_sources = [(r["id"], source_by_file[f]) for r in facts["legendary_assault_tips"] for f in r["source_images"]]
    sql.append("INSERT INTO knowledge.legendary_assault_tips (id,encounter_name,exact_visible_text,review_state) VALUES" + values(tip_rows) + "\nON CONFLICT (id) DO UPDATE SET encounter_name=EXCLUDED.encounter_name,exact_visible_text=EXCLUDED.exact_visible_text,review_state=EXCLUDED.review_state;\n")
    sql.append("INSERT INTO knowledge.legendary_assault_tip_sources (tip_id,source_id) VALUES" + values(tip_sources) + "\nON CONFLICT DO NOTHING;\n")
    special_factions = {
        "Blacks": "audit-faction-blacks", "Brotherhood": "audit-faction-brotherhood",
        "Greyjoy": "audit-faction-greyjoy", "Bolton": "audit-faction-bolton",
    }
    faction_id = lambda name: special_factions.get(name, "sqlite-faction-" + name.encode().hex())
    faction_names = list(dict.fromkeys(r["faction"] for r in facts["faction_rules"]))
    sql.append("INSERT INTO knowledge.factions (id,name,live_status) VALUES" + values((faction_id(name), name, "live") for name in faction_names) + "\nON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,live_status=EXCLUDED.live_status;\n")
    faction_rows = [(r["id"], faction_id(r["faction"]), r["exact_visible_text"], "live", source_by_file[r["source_images"][0]], None) for r in facts["faction_rules"]]
    faction_sources = [(r["id"], source_by_file[f]) for r in facts["faction_rules"] for f in r["source_images"]]
    sql.append("INSERT INTO knowledge.faction_rules (id,faction_id,exact_text,live_status,source_id,announced_update_id) VALUES" + values(faction_rows) + "\nON CONFLICT (id) DO UPDATE SET faction_id=EXCLUDED.faction_id,exact_text=EXCLUDED.exact_text,live_status=EXCLUDED.live_status,source_id=EXCLUDED.source_id,announced_update_id=EXCLUDED.announced_update_id;\n")
    sql.append("INSERT INTO knowledge.faction_rule_sources (rule_id,source_id) VALUES" + values(faction_sources) + "\nON CONFLICT DO NOTHING;\n")

    team_rows = []
    member_rows = []
    for key, members in facts["observed_teams"]:
        filename_num = key.split("-")[0]
        example_id = "drive-observed-" + key
        team_rows.append((example_id, "observed_composition", None, None, "not_shown", source_by_file[f"IMG_{filename_num}.PNG"], "screenshot_checked_composition_only"))
        member_rows.extend((example_id, position, name) for position, name in enumerate(members, 1))
    sql.append("INSERT INTO knowledge.community_team_examples (id,mode,displayed_team_power,leader_position,outcome,source_id,review_state) VALUES" + values(team_rows) + "\nON CONFLICT (id) DO UPDATE SET mode=EXCLUDED.mode,displayed_team_power=EXCLUDED.displayed_team_power,leader_position=EXCLUDED.leader_position,outcome=EXCLUDED.outcome,source_id=EXCLUDED.source_id,review_state=EXCLUDED.review_state;\n")
    sql.append("INSERT INTO knowledge.community_team_members (example_id,position,observed_name) VALUES" + values(member_rows) + "\nON CONFLICT (example_id,position) DO UPDATE SET observed_name=EXCLUDED.observed_name;\n")

    evidence = []
    evidence.extend(("war_outpost_rule", r["id"], source_by_file[r["source_image"]], "exact_visible_rule", "visually_verified") for r in facts["war_outpost_rules"])
    evidence.extend(("legendary_assault_tip", r["id"], source_by_file[f], "exact_visible_tip", "visually_verified") for r in facts["legendary_assault_tips"] for f in r["source_images"])
    evidence.extend(("faction_rule", r["id"], source_by_file[f], "exact_visible_rule", "visually_verified") for r in facts["faction_rules"] for f in r["source_images"])
    evidence.extend(("community_team_example", row[0], row[5], "observed_composition_only", "screenshot_checked_no_outcome") for row in team_rows)
    existing_war = {"IMG_2132.PNG":"barricade","IMG_2136.PNG":"stone-keep","IMG_2137.PNG":"maesters-sigil","IMG_2138.PNG":"baratheon-war-camp"}
    evidence.extend(("war_outpost_rule", record, source_by_file[filename], "duplicate_exact_visible_rule", "visually_verified") for filename, record in existing_war.items())
    sql.append("INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES" + values(evidence) + "\nON CONFLICT DO NOTHING;\n")

    sql.append("""DO $$
BEGIN
  IF (SELECT count(*) FROM knowledge.source_review_resolutions WHERE review_state='individually_visually_reviewed') < 345 THEN RAISE EXCEPTION 'Expected 345 final source reviews'; END IF;
  IF (SELECT count(*) FROM knowledge.war_outpost_rules) < 9 THEN RAISE EXCEPTION 'Expected at least nine War outpost rules'; END IF;
  IF (SELECT count(*) FROM knowledge.legendary_assault_tips) <> 9 THEN RAISE EXCEPTION 'Expected nine Legendary Assault tips'; END IF;
  IF (SELECT count(*) FROM knowledge.faction_rules) <> 16 THEN RAISE EXCEPTION 'Expected sixteen faction rules'; END IF;
  IF (SELECT count(*) FROM knowledge.community_team_examples WHERE outcome <> 'not_shown') <> 0 THEN RAISE EXCEPTION 'Observed compositions must not assert outcomes'; END IF;
END $$;
""")
    OUTPUT.write_text("\n".join(sql))
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
