-- Exact mechanics visually transcribed from the 20 original ally-card PNGs.
-- Historical screenshots do not establish current release state.
ALTER TABLE knowledge.ally_gem_cards
  ADD COLUMN IF NOT EXISTS relationship text,
  ADD COLUMN IF NOT EXISTS replaces_power_up text,
  ADD COLUMN IF NOT EXISTS exact_visible_effect text,
  ADD COLUMN IF NOT EXISTS currentness_state text;

UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Khal Drogo', ally_name_candidate='Daenerys Targaryen - Khaleesi of the Great Grass Sea', gem_title_candidate='Sun and Stars Gem', relationship='Power of Love', replaces_power_up='Area Clear Power-Ups', exact_visible_effect='When activated, this Gem grants the team Leader +10% Stamina and HEALS them for 5% Max HP.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2537';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2537' AND source_id=102537;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Davos Seaworth', ally_name_candidate='Stannis Baratheon - The One True King', gem_title_candidate='Law and Justice', relationship='Oathsworn', replaces_power_up='Vertical Clear Power-Ups', exact_visible_effect='When activated, this Gem REMOVES up to 2 Buffs from 2 random enemies.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2538';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2538' AND source_id=102538;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Rhaenys Targaryen', ally_name_candidate='Meleys - The Red Queen', gem_title_candidate='Off to Battle Again, Old Girl', relationship='Monsters and Men', replaces_power_up='Color Clear Power-Ups', exact_visible_effect='When activated, this gem STUNS all enemies for 1 turn and WOUNDS them for 3 turns.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2539';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2539' AND source_id=102539;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Daenerys Targaryen', ally_name_candidate='Grey Worm - Leader of the Unsullied', gem_title_candidate='Breaker of Chains', relationship='Oathsworn', replaces_power_up='Vertical Clear Power-Ups', exact_visible_effect='When activated, this Gem afflicts up to 2 random enemies with FIRE.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2540';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2540' AND source_id=102540;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Tyrion Lannister', ally_name_candidate='Bronn - Sellsword for Hire', gem_title_candidate='Paid to Kill Gem', relationship='Oathsworn', replaces_power_up='Vertical Clear Power-Ups', exact_visible_effect='When activated, this Gem deals 25% ATK Physical Damage to an enemy marked with BRONN''S DAGGER.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2541';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2541' AND source_id=102541;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Stannis Baratheon', ally_name_candidate='Melisandre - The Red Woman', gem_title_candidate='Azor Ahai Proclaimed', relationship='Oathsworn', replaces_power_up='Vertical Clear Power-Ups', exact_visible_effect='When activated, this Gem grants all allies +15% Gem Damage for 3 turns.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2542';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2542' AND source_id=102542;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Rhaenyra Targaryen', ally_name_candidate='Criston Cole - Personal Escort', gem_title_candidate='Love and Duty Gem', relationship='Oathsworn', replaces_power_up='Vertical Clear Power-Ups', exact_visible_effect='When activated, this Gem provides a +15% DEF Buff to the ally marked with CRISTON''S CHARGE for 3 turns.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2543';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2543' AND source_id=102543;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='The Night King', ally_name_candidate='Icy Viserion - Dragon of the Night King', gem_title_candidate='Awakened Horror', relationship='Monsters and Men', replaces_power_up='Color Clear Power-Ups', exact_visible_effect='When activated, this gem afflicts all enemies with 1 ICE, 3 FIRE and -15% Unnatural Resistance. Dragons take double the effects.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2544';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2544' AND source_id=102544;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Laenor Velaryon', ally_name_candidate='Corlys Velaryon - Lord of the Tides', gem_title_candidate='United in Blood', relationship='Flesh and Blood', replaces_power_up='Horizontal Clear Power-Ups', exact_visible_effect='When activated, this gem afflicts 2 random enemies with 1 RAID.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2545';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2545' AND source_id=102545;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Arya Stark', ally_name_candidate='Sansa Stark - Lady of Winterfell', gem_title_candidate='Sisters Reunited Gem', relationship='Flesh and Blood', replaces_power_up='Horizontal Clear Power-Ups', exact_visible_effect='When activated, this Gem grants all allies +25% Tenacity for 3 turns, and marks the enemy struck with ARYA''S LIST for 3 turns.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2546';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2546' AND source_id=102546;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Daemon Targaryen', ally_name_candidate='Caraxes - The Blood Wyrm', gem_title_candidate='Dragons Made Us Kings', relationship='Monsters and Men', replaces_power_up='Color Clear Power-Ups', exact_visible_effect='When activated, this gem grants all team members 1 FURY and all Dragons gain 20% Stamina.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2547';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2547' AND source_id=102547;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Ned Stark', ally_name_candidate='Catelyn Stark - The Lady of Winterfell', gem_title_candidate='Wardens of the North Gem', relationship='Flesh and Blood', replaces_power_up='Horizontal Clear Power-Ups', exact_visible_effect='When activated, this Gem grants all Stark allies +10% Physical Resistance for 3 turns.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2548';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2548' AND source_id=102548;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Jon Snow', ally_name_candidate='Ghost - Jon Snow''s Direwolf', gem_title_candidate='A King and His Wolf Gem', relationship='Monsters and Men', replaces_power_up='Color Clear Power-Ups', exact_visible_effect='When activated, this Gem deals a bonus 25% ATK Physical Damage to BRITTLE enemies.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2549';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2549' AND source_id=102549;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Jaime Lannister', ally_name_candidate='Cersei Lannister - Queen of the Andals and the First Men', gem_title_candidate='Anything for Love Gem', relationship='Power of Love', replaces_power_up='Area Clear Power-Ups', exact_visible_effect='When activated, this Gem WOUNDS and DECEIVES all enemies for 1 turn.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2550';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2550' AND source_id=102550;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Benjen Stark', ally_name_candidate='Yoren - Recruiter of the Night''s Watch', gem_title_candidate='Southern Crows', relationship='Brothers in Arms', replaces_power_up='Seeker Power-Ups', exact_visible_effect='When activated, this Gem grants the Weakest ally a 5% HP Pool SHIELD.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2551';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2551' AND source_id=102551;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Tormund Giantsbane', ally_name_candidate='Wun Wun - The Last of His Kind', gem_title_candidate='Giant Slayers', relationship='Brothers in Arms', replaces_power_up='Seeker Power-Ups', exact_visible_effect='When activated, this Gem deals 50% Current Stamina damage to target.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2552';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2552' AND source_id=102552;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Beric Dondarrion', ally_name_candidate='Thoros of Myr - The Red Priest Warrior', gem_title_candidate='The Brotherhood Gem', relationship='Brothers in Arms', replaces_power_up='Seeker Power-Ups', exact_visible_effect='When activated, this Gem HEALS the Weakest member of the team by 5% Max HP.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2553';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2553' AND source_id=102553;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Roose Bolton', ally_name_candidate='Walder Frey - Lord of the Riverlands', gem_title_candidate='Malevolent Conspirators', relationship='Brothers in Arms', replaces_power_up='Seeker Power-Ups', exact_visible_effect='When activated, this Gem afflicts 2 random enemies with BLEED.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2554';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2554' AND source_id=102554;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Joffrey Baratheon', ally_name_candidate='Margaery Tyrell - The Lady of House Tyrell', gem_title_candidate='Royal Couple', relationship='Power of Love', replaces_power_up='Area Clear Power-Ups', exact_visible_effect='When activated, this gem HEALS the Weakest member of the team by 5% Current HP, grants them 1 RENEW, and adds 1 Gold to the TREASURY.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2555';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2555' AND source_id=102555;
UPDATE knowledge.ally_gem_cards SET owner_name_candidate='Viserys Targaryen I', ally_name_candidate='Alicent Hightower - Queen Dowager', gem_title_candidate='Political Marriage', relationship='Flesh and Blood', replaces_power_up='Horizontal Clear Power-Ups', exact_visible_effect='When activated, this gem will PACIFY a random enemy and Viserys for 2 turns. Viserys also gains 1 RENEW.', review_state='visually_verified', currentness_state='historical_currentness_unknown' WHERE id='ally-gem-2556';
UPDATE knowledge.record_evidence SET review_state='visually_verified' WHERE record_kind='ally_gem_card' AND record_id='ally-gem-2556' AND source_id=102556;
ALTER TABLE knowledge.ally_gem_cards ALTER COLUMN relationship SET NOT NULL, ALTER COLUMN replaces_power_up SET NOT NULL, ALTER COLUMN exact_visible_effect SET NOT NULL, ALTER COLUMN currentness_state SET NOT NULL;
