-- Duplicate or continuation dragon screens, linked as identity evidence only.
INSERT INTO knowledge.legendary_assault_ability_sources (ability_id, source_id) VALUES
  ('viserion-claw-swipe-ii', 102595),
  ('viserion-claw-swipe-ii', 102597),
  ('viserion-claw-swipe-ii', 102598),
  ('viserion-own-pace', 102596),
  ('viserion-own-pace', 102599),
  ('viserion-rude-awakening-ii', 102600),
  ('viserion-rude-awakening-ii', 102601),
  ('viserion-golden-scales', 102602),
  ('viserion-patience-ii', 102603),
  ('viserion-patience-ii', 102604),
  ('viserion-patience-ii', 102605),
  ('viserion-unchained-dragon', 102606),
  ('viserion-unchained-dragon', 102607),
  ('rhaegal-sqlite-1', 102657),
  ('rhaegal-sqlite-1', 102658),
  ('rhaegal-sqlite-2', 102659),
  ('rhaegal-sqlite-3', 102660),
  ('rhaegal-sqlite-3', 102661),
  ('rhaegal-sqlite-3', 102662),
  ('rhaegal-sqlite-6', 102663),
  ('rhaegal-sqlite-6', 102664),
  ('rhaegal-sqlite-5', 102665),
  ('rhaegal-sqlite-5', 102666),
  ('rhaegal-sqlite-4', 102667),
  ('rhaegal-sqlite-4', 102668)
ON CONFLICT DO NOTHING;
INSERT INTO knowledge.record_evidence (record_kind, record_id, source_id, evidence_role, review_state) VALUES
  ('legendary_assault_ability', 'viserion-claw-swipe-ii', 102595, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-claw-swipe-ii', 102597, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-claw-swipe-ii', 102598, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-own-pace', 102596, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-own-pace', 102599, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-rude-awakening-ii', 102600, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-rude-awakening-ii', 102601, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-golden-scales', 102602, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-patience-ii', 102603, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-patience-ii', 102604, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-patience-ii', 102605, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-unchained-dragon', 102606, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'viserion-unchained-dragon', 102607, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-1', 102657, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-1', 102658, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-2', 102659, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-3', 102660, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-3', 102661, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-3', 102662, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-6', 102663, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-6', 102664, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-5', 102665, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-5', 102666, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-4', 102667, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review'),
  ('legendary_assault_ability', 'rhaegal-sqlite-4', 102668, 'ocr_ability_identity_only', 'ability_identity_ocr_pending_visual_review')
ON CONFLICT DO NOTHING;
