-- Deterministic portrait crops from byte-verified full profile screenshots.
-- Original screenshots and direct evidence links remain preserved.
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-audit-variant-criston-kingmaker', 'audit-variant-criston-kingmaker', 'derived:audit-variant-criston-kingmaker', 'assets/champion-portraits/derived-audit-variant-criston-kingmaker.png', 'scripts/build-derived-portraits.py', '3db1f785fc5d05d9ba00bad3f2aaa994d9cca6f2d6944fad1bd93affd486e135', '102318', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-audit-variant-criston-kingmaker', '102318', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-audit-variant-jon-battle-of-the-bastards', 'audit-variant-jon-battle-of-the-bastards', 'derived:audit-variant-jon-battle-of-the-bastards', 'assets/champion-portraits/derived-audit-variant-jon-battle-of-the-bastards.png', 'scripts/build-derived-portraits.py', '076873f1c1dc355239f8e4dd71bb8d22b7411d97f037feb79a8bc14a0d5a8ad6', '102411', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-audit-variant-jon-battle-of-the-bastards', '102411', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-audit-variant-stannis-one-true-king', 'audit-variant-stannis-one-true-king', 'derived:audit-variant-stannis-one-true-king', 'assets/champion-portraits/derived-audit-variant-stannis-one-true-king.png', 'scripts/build-derived-portraits.py', 'c772ad5a177dd6d4a5477765c9a869b25baad9a1c8e59f97dc1764b0c329bceb', '102272', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-audit-variant-stannis-one-true-king', '102272', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-legacy-champion-caraxes', 'legacy-champion-caraxes', 'derived:legacy-champion-caraxes', 'assets/champion-portraits/derived-legacy-champion-caraxes.png', 'scripts/build-derived-portraits.py', '792231d0314e57c57d557b17f7a1430aa53128c9eef0db867a96142d43c9ff4f', '102296', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-legacy-champion-caraxes', '102296', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-legacy-champion-wunwun', 'legacy-champion-wunwun', 'derived:legacy-champion-wunwun', 'assets/champion-portraits/derived-legacy-champion-wunwun.png', 'scripts/build-derived-portraits.py', '1ef5b720a37bfc683888d8e6ae2b16b97a100b56791ebdbb79a8c8560d2ace21', '102314', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-legacy-champion-wunwun', '102314', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-11', 'sqlite-champion-11', 'derived:sqlite-champion-11', 'assets/champion-portraits/derived-sqlite-champion-11.png', 'scripts/build-derived-portraits.py', 'e2d68ed6ec734e104e008357f2d9e54135d80fbdd9bd93a811f7473383363370', '101944', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-11', '101944', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-17', 'sqlite-champion-17', 'derived:sqlite-champion-17', 'assets/champion-portraits/derived-sqlite-champion-17.png', 'scripts/build-derived-portraits.py', '4e7d86c57ffa780e20b79e2177d204b83cb39303b08edef224cbd72dd805cce5', '101977', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-17', '101977', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-18', 'sqlite-champion-18', 'derived:sqlite-champion-18', 'assets/champion-portraits/derived-sqlite-champion-18.png', 'scripts/build-derived-portraits.py', 'd522728b93db67ec5da522afced4d9fe71c68b4461023d2fd7f484e1b9a8a71e', '101982', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-18', '101982', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-19', 'sqlite-champion-19', 'derived:sqlite-champion-19', 'assets/champion-portraits/derived-sqlite-champion-19.png', 'scripts/build-derived-portraits.py', '05e9a0db6b538ee179da92e8d08f7b307f5a30c4a1afa63c9ef5118e246ea3df', '101992', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-19', '101992', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-20', 'sqlite-champion-20', 'derived:sqlite-champion-20', 'assets/champion-portraits/derived-sqlite-champion-20.png', 'scripts/build-derived-portraits.py', '484cfff9972ea82fda89d82b76e8c215eb5a9c4de0b8fede28c1406acd9ea4ba', '101997', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-20', '101997', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-24', 'sqlite-champion-24', 'derived:sqlite-champion-24', 'assets/champion-portraits/derived-sqlite-champion-24.png', 'scripts/build-derived-portraits.py', 'bc63d6729d6894d454d31a1e8fb5c19c5ba17342b103f223969f0e827c3e345b', '102041', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-24', '102041', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-29', 'sqlite-champion-29', 'derived:sqlite-champion-29', 'assets/champion-portraits/derived-sqlite-champion-29.png', 'scripts/build-derived-portraits.py', 'c4b5a16d00b440a08e45d5f6df905a740f9271abcf1acf87adcc1a53421c416a', '102071', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-29', '102071', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-41', 'sqlite-champion-41', 'derived:sqlite-champion-41', 'assets/champion-portraits/derived-sqlite-champion-41.png', 'scripts/build-derived-portraits.py', '4847bb43772a64fa73722c8de8086d81d8f384690f22d67a229c91c2c3db7cc2', '102160', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-41', '102160', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-51', 'sqlite-champion-51', 'derived:sqlite-champion-51', 'assets/champion-portraits/derived-sqlite-champion-51.png', 'scripts/build-derived-portraits.py', '9c01664bf23440ec400ec9316762c348a84c7edb7ae1abd825088a49bc7bf4db', '102435', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-51', '102435', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-54', 'sqlite-champion-54', 'derived:sqlite-champion-54', 'assets/champion-portraits/derived-sqlite-champion-54.png', 'scripts/build-derived-portraits.py', '2d81bdb3cc6efa30e01766cda372451a69c7438cb8762e7aae816067812b57c6', '102257', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-54', '102257', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-6', 'sqlite-champion-6', 'derived:sqlite-champion-6', 'assets/champion-portraits/derived-sqlite-champion-6.png', 'scripts/build-derived-portraits.py', 'b64a8397e8939b4781b9fe15e542071f5a9ea464a127f90f8d693a6533d042ab', '101906', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-6', '101906', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-65', 'sqlite-champion-65', 'derived:sqlite-champion-65', 'assets/champion-portraits/derived-sqlite-champion-65.png', 'scripts/build-derived-portraits.py', '037d8a5a1db40a69fcd3a25a2cdad845b088e2e819818e5bf0c09dd8cf869362', '102372', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-65', '102372', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-66', 'sqlite-champion-66', 'derived:sqlite-champion-66', 'assets/champion-portraits/derived-sqlite-champion-66.png', 'scripts/build-derived-portraits.py', '986b5748bde299c9d14635838118a18c27df8bf7414881de795a69d877923a4b', '102322', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-66', '102322', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-68', 'sqlite-champion-68', 'derived:sqlite-champion-68', 'assets/champion-portraits/derived-sqlite-champion-68.png', 'scripts/build-derived-portraits.py', '7a07a171edd380f11592ca722c7995374e190fa5573fef2a234e4c0b815a1b96', '102336', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-68', '102336', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-70', 'sqlite-champion-70', 'derived:sqlite-champion-70', 'assets/champion-portraits/derived-sqlite-champion-70.png', 'scripts/build-derived-portraits.py', '0a3210b0bc33f622a1b0bfe9722961cbefd2548dbdc1b87f31957b44bd8a9d88', '102343', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-70', '102343', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-72', 'sqlite-champion-72', 'derived:sqlite-champion-72', 'assets/champion-portraits/derived-sqlite-champion-72.png', 'scripts/build-derived-portraits.py', '23829afe8fa00cff481a7b2dbfe0341ab27a49308ae3ff412d163ce33da762e4', '102429', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-72', '102429', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-74', 'sqlite-champion-74', 'derived:sqlite-champion-74', 'assets/champion-portraits/derived-sqlite-champion-74.png', 'scripts/build-derived-portraits.py', '54ccb1c6170dabb1db9de252932e84f9ef59b1453bc470afbcc25584a86d3b8a', '102360', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-74', '102360', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-75', 'sqlite-champion-75', 'derived:sqlite-champion-75', 'assets/champion-portraits/derived-sqlite-champion-75.png', 'scripts/build-derived-portraits.py', '6ebc5405ae25d8ac8da16a5f20877a55596c689dee6cc77fc99d8f050dec82a0', '102367', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-75', '102367', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-78', 'sqlite-champion-78', 'derived:sqlite-champion-78', 'assets/champion-portraits/derived-sqlite-champion-78.png', 'scripts/build-derived-portraits.py', 'e39a2f02d2bf33282545a7b4d5ad002c4e89823ae846f9d9b4c143f50f3f352e', '102424', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-78', '102424', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
INSERT INTO knowledge.champion_portraits (id,variant_id,legacy_key,asset_path,source_script,sha256,source_image_id,attribution,review_state) VALUES ('derived-profile-sqlite-champion-80', 'sqlite-champion-80', 'derived:sqlite-champion-80', 'assets/champion-portraits/derived-sqlite-champion-80.png', 'scripts/build-derived-portraits.py', '7278163f34661bf1bb77949f68ba8558563273b2c23df6dc2d4b9e98d2f127f2', '102392', 'User supplied GOT: Legends game image; game art remains with its rights holder.', 'derived_profile_center_crop') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id, asset_path=EXCLUDED.asset_path, sha256=EXCLUDED.sha256, source_image_id=EXCLUDED.source_image_id, review_state=EXCLUDED.review_state;
INSERT INTO knowledge.record_evidence (record_kind,record_id,source_id,evidence_role,review_state) VALUES ('champion_portrait', 'derived-profile-sqlite-champion-80', '102392', 'derived_from_full_profile_screenshot', 'derived_profile_center_crop') ON CONFLICT DO NOTHING;
DO $$
BEGIN
  IF (SELECT count(*) FROM knowledge.champion_portraits WHERE review_state='derived_profile_center_crop') <> 25 THEN
    RAISE EXCEPTION 'Expected 25 derived profile portraits';
  END IF;
END $$;
